### PR TITLE
fix and improve sysctl sed cmd

### PR DESCRIPTION
**Pull request by jmontleon**

### CODE REVIEW

**Comment by jmontleon** [comment]
Original command was missing a backslash and was just adding empty lines to the sysctl.conf.

This generated output from the installer like:
sh: t.ipv4.ip_forward: command not found
sh: t.ipv4.ip_forward: command not found
sh: t.ipv4.ip_forward: command not found
sh: t.ipv4.ip_forward: command not found
sh: t.ipv4.ip_forward: command not found
sh: t.ipv4.ip_forward: command not found
net.ipv4.ip_forward = 1

Even after it was fixed, each subsequent run would produce additional lines that read:
net.ipv4.ip_forward = 1

Tested and ensured that this sed command will add 'net.ipv4.ip_forward =1' if a 'net.ipv4.ip_forward' line does not exist and will replace any existing 'net.ipv4.ip_forward' line with 'net.ipv4.ip_forward =1', but not add more if one or more does exists. Does not harm other lines in the file.

**Comment by jmontleon** [comment]
@knowncitizen @tzumainn can one or both of you review this when you have a moment?

**Comment by rwsu** [comment]
I just tested it. Looks good to me.

**Comment by knowncitizen** [comment]
ACK

**Pull request merged**
