### PR TITLE
add a method to allow deleting a node

### PR DESCRIPTION
**Pull request by sdherr**
SSIA

### CODE REVIEW

**Comment by knowncitizen** [comment]
Do we have any idea when this might land in Fog? I'd like to  have another patch that changes the fog requirement.

**Comment by knowncitizen** [comment]
Also this appears to fix #44

**Comment by sdherr** [comment]
They already merged the patch, so #nextversion, which appears to be 1.36.

**Comment by knowncitizen** [comment]
I'm going to merge this

**Pull request merged**
