### PR TITLE
leave or set selinux in enforcing

### PR DESCRIPTION
**Pull request by jmontleon**

### CODE REVIEW

**Comment by jmontleon** [comment]
For POST_INSTALL_8 we set enforcing. For some reason POST_INSTALL_10 ended up setting permissive, but either way this is a temporary change and I have done numerous deployments after a reboot and back in enforcing.

**Comment by jmontleon** [comment]
Confirmed setup and deployment were successful leaving selinux in enforcing.

**Comment by knowncitizen** [comment]
Enforcing good, permissive bad.

**Comment by knowncitizen** [comment]
:+1:

**Pull request merged**
