### PR TITLE
better handle swift failures and unavailability

### PR DESCRIPTION
**Pull request by jmontleon**

### CODE REVIEW

**Comment by jmontleon** [comment]
This will attempt to get swift started and responding before it allows other work to be attempted. 

It will also end with a message in the event swift can be made responsive, "Swift did not start properly. Please fix the problem before trying again" rather than letting it get buried by the port checks and flavor deletions in order to make it clear the installation was not successfully completed.

**Comment by jmontleon** [comment]
@knowncitizen @tzumainn can one or both of you review this when you have a moment?

**Comment by tzumainn** [comment]
Ah, so now you also restart swift?  That makes sense to me; I know I've had to do similar things with other OpenStack services from the command line.  :+1: from me

**Comment by jmontleon** [comment]
Yes. There is a bugzilla open and a fix upstream for swift services failing to start because the ring files are not yet created. In all likelihood it should take just one attempt to restart the service for us to be good, but I limited it to a handful of retries as of course when jsaucier tried the last fix he of course got stuck in an infinite loop because swift-proxy had failed to start, which is definitely not desirable.

**Comment by knowncitizen** [comment]
ACK

**Pull request merged**
