### PR TITLE
Refactor egon to work with rhci-tripleo-api

### PR DESCRIPTION
**Pull request by tzumainn**

### CODE REVIEW

**Comment by knowncitizen** [comment]
I'm having trouble with getting this test to pass.  NACK for now.

```
[root@instack egon]# rspec test/test_undercloud_handle.rb
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- fog/openstack/models/image/image (LoadError)
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /root/egon/test/test_undercloud_handle.rb:4:in `<top (required)>'
    from /usr/local/share/gems/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1226:in `load'
    from /usr/local/share/gems/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1226:in `block in load_spec_files'
    from /usr/local/share/gems/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1224:in `each'
    from /usr/local/share/gems/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1224:in `load_spec_files'
    from /usr/local/share/gems/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:97:in `setup'
    from /usr/local/share/gems/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:85:in `run'
    from /usr/local/share/gems/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:70:in `run'
    from /usr/local/share/gems/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:38:in `invoke'
    from /usr/local/share/gems/gems/rspec-core-3.2.3/exe/rspec:4:in `<top (required)>'
    from /usr/local/bin/rspec:23:in `load'
    from /usr/local/bin/rspec:23:in `<main>'
```

The other two tests run fine, but undercloud_handle fails.

**Comment by knowncitizen** [comment]
Note, this is a fresh CentOS 7 install with a fresh RHOSP8 install.

**Comment by tzumainn** [comment]
Does the test pass for you on master?

**Comment by knowncitizen** [comment]
Looks like the #57 fixed most of the tests and this fixes the rest.  Thanks!

**Comment by knowncitizen** [comment]
ACK, merging.

**Pull request merged**
